boyroid/source:
  - source: 'sync-testing/files/'
    dest: 'sync-testing/files/'
    exclude: 'folder3/file4.txt'
  - source: 'sync-testing/roles/'
    dest: 'sync-testing/roles/'
    exclude: |
      backend/defaults/main.yml
      database/defaults/main.yml
      frontend/defaults/main.yml
      nginx/defaults/main.yml

boyroid/destination:
  - source: 'sync-testing/files/'
    dest: 'sync-testing/files/'
    exclude: 'folder3/file4.txt'
  - source: 'sync-testing/roles/'
    dest: 'sync-testing/roles/'
    exclude: |
      backend/defaults/main.yml
      database/defaults/main.yml
      frontend/defaults/main.yml
      nginx/defaults/main.yml
