boyroid/source:
  - source: 'sync-testing/files/'
    dest: 'sync-testing/files/'
    exclude: 'folder3/file4.txt'

boyroid/destination:
  - source: 'sync-testing/files/'
    dest: 'sync-testing/files/'
    exclude: 'folder3/file4.txt'
